server:
  port: 8080


#add spring datasource config
spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/data_test
    username: postgres
    password: 123456
    driver-class-name: org.postgresql.Driver
#  jpa:
#    properties:
#      hibernate:
#        default_schema: public
#    show_sql: true
#  flyway:
#    schemas: public
#    locations: classpath:db/migration
#    enabled: true

  output:
    ansi:
      enabled: ALWAYS
