server:
  port: 8080

typi-code-client:
  base-url: https://jsonplaceholder.typicode.com
  get-album-path: /albums

spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/data_test
    username: postgres
    password: postgres
  jpa:
    properties:
      hibernate:
        default_schema: public
    show_sql: true
  flyway:
    schemas: public
    locations: classpath:db/migration
    enabled: true
  output:
    ansi:
      enabled: ALWAYS
ff4j:
  api:
    context-path: /v1/ff4j
    spring-doc:
      enabled: true

logging:
  level:
    org:
      springframework: DEBUG
    com:
      example:
        demo: DEBUG
#        security: DEBUG